services:
  newsletter-app:
    build:
      context: .
    container_name: newsletter-app
    ports:
      - "3000:3000"        # App listens on port 3000
    env_file:
      - .env               # Loads DATABASE_URL, DIRECT_URL, API keys, etc.
    restart: unless-stopped
