services:
  newsletter-app:
    build:
      context: .
    container_name: newsletter-app
    ports:
      - "3000:3000"
    env_file:
      - .env        # runtime secrets only
    restart: always


