services:
  newsletter-app:
    build:
      context: .
      dockerfile: dockerfile   # change to Dockerfile if that's your filename
    container_name: newsletter-app
    env_file:
      - .env
    expose:
      - "3000"                 # internal-only; no host port publish
    networks:
      - boltluna-net
    restart: unless-stopped

networks:
  boltluna-net:
    external: true
